spring:
  profiles:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5432/customers_db
    username: postgres
    password: 420189
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  aop.proxy-target-class: true